Repository Web3-Bharat-ITER/UI-Component-Library, pull requests merged in 2022-10, with the labels that each got.

#6 Added documentation for contribution guidelines
  README.md
Labels: hacktoberfest2022

#16 Login_page
  Login_page/background.webp
  Login_page/index.html
  Login_page/styles.css
Labels: hacktoberfest2022

#30 Ananya
  hover card/1.jpg
  hover card/2.jpg
  hover card/3.jpg
  hover card/4.jpg
  hover card/index.html
  hover card/style.css
Labels: enhancement, hacktoberfest2022

#58 Added contact.html, contact.css. Added a new file app.js and some images
  Contact_form/app.js
  Contact_form/contact.css
  Contact_form/contact.html
  Contact_form/img/email.png
  Contact_form/img/location.png
  Contact_form/img/phone.png
  Contact_form/img/shape.png
Labels: enhancement, hacktoberfest2022

#61 Added "Page-3" in "Login Page" folder
  Login_page/Page-3/index.html
  Login_page/Page-3/style.css
Labels: enhancement, hacktoberfest2022, hacktober-accepted

#70 added sliding photos
  sliding photos/5.webp
  sliding photos/baby.webp
  sliding photos/dog and women.jpg
  sliding photos/father and son.jpg
  sliding photos/girl.jpg
  sliding photos/index.html
  sliding photos/love.webp
  sliding photos/style.css
Labels: enhancement, hacktoberfest2022, hacktober-accepted

#71 Added "Footer-2" in "Footer-Section" folder.
  Footer-Section/Footer-2/footer.css
  Footer-Section/Footer-2/footer.html
  Footer-Section/Footer-2/logo.png
Labels: enhancement, hacktoberfest2022, hacktober-accepted

#76 fix overflow of project cards
  UI-Component-Library-design-files/css/styles.css
Labels: enhancement, hacktoberfest2022, hacktober-accepted

#82 Added a Checkout Form
  Checkout Form/checkout.css
  Checkout Form/checkout.html
  Checkout Form/checkout.png
Labels: hacktoberfest2022, hacktober-accepted

#78 Added Roadmap Component
  Roadmap Component/index.html
  Roadmap Component/readme.md
Labels: hacktoberfest2022, hacktober-accepted

#84 loading screen component
  Loading Screen/index.html
  Loading Screen/style.css
Labels: hacktoberfest2022, hacktober-accepted

#88 Quiz Component UI || issue #86
  Quiz UI Components/Image1.jpg
  Quiz UI Components/README
  Quiz UI Components/Screenshot (200).png
  Quiz UI Components/Screenshot (201).png
  Quiz UI Components/index.html
  Quiz UI Components/script.js
  Quiz UI Components/style.css
Labels: hacktoberfest2022, hacktober-accepted

#92 Added Login Page
  Login Page/Google.png
  Login Page/Login Page.html
  Login Page/WebDev.jpg
  Login Page/sstyle3.css
Labels: hacktoberfest2022, hacktober-accepted

#93 Ads Manager UI added
  Ads Manager/Ads Manager.html
  Ads Manager/Ads.jpg
  Ads Manager/Styling.css
Labels: hacktoberfest2022, hacktober-accepted

#94 Movie Card Components added.
  Movie Card Component/index.html
Labels: hacktoberfest2022, hacktober-accepted

#97 Create ion card
  ion card
Labels: hacktoberfest2022, hacktober-accepted

#121 Added home page
  Home page/images/banner.png
  Home page/index.html
  Home page/style.css
Labels: hacktoberfest2022, hacktober-accepted

#120 mapping created
  mapping/FD.PNG
  mapping/map.html
Labels: enhancement, hacktoberfest2022, hacktober-accepted

#124 REGISTRATION FORM created
  Registration form/form.html
Labels: hacktoberfest2022, hacktober-accepted

#125 add Comets Animated Background
  Comets-Animated-Background/README.md
  Comets-Animated-Background/comets.png
  Comets-Animated-Background/index.html
  Comets-Animated-Background/styles.css
  index.html
Labels: hacktoberfest2022, hacktober-accepted

#126 Added Sattyam Navbar in Navbar Folder
  Nav-bar/Sattyam Navbar/Navbar.png
  Nav-bar/Sattyam Navbar/README.md
  Nav-bar/Sattyam Navbar/index.html
  Nav-bar/Sattyam Navbar/style.css
Labels: hacktoberfest2022, hacktober-accepted

#127 Added avatar card
  avatar_card/index.html
  avatar_card/loader.css
  avatar_card/style.css
Labels: hacktoberfest2022, hacktober-accepted

#133 Add another loading
  Loading-pure-css/index.html
  Loading-pure-css/styles.css
  index.html
Labels: hacktoberfest2022, hacktober-accepted

#132 add profile card
  profileCard/avatarPic.jpg
  profileCard/index.html
  profileCard/style.css
Labels: hacktoberfest2022, hacktober-accepted

#130 Added Hovering card with html and css Grid View
  hover card/Hovercard.html
Labels: hacktoberfest2022, hacktober-accepted

#128 added a navbar (issue #114)
  Nav-bar/Nav-bar 4/navBar.html
Labels: hacktoberfest2022, hacktober-accepted

#134 prep created
  PLACEMENT PREP/placementcon.png
  PLACEMENT PREP/prep.css
  PLACEMENT PREP/prep.html
Labels: hacktoberfest2022, hacktober-accepted

#136 ESHOP created
  ESHOP/eshop.css
  ESHOP/eshop.html
  ESHOP/images/gro.png
  ESHOP/images/gt.png
  ESHOP/images/healthwell.jpg
  ESHOP/images/home.png
Labels: hacktoberfest2022, hacktober-accepted

#135 added background animation and login card
  animation_background/index.html
  animation_background/style.css
Labels: hacktoberfest2022, hacktober-accepted

#131 Resources file added having UI elements, element library
  dracula-ui-2021-04-16.fig
Labels: hacktoberfest2022, hacktober-accepted

#138 kishanlal-Login Page Added
  kishanlal-login-page/index.html
  kishanlal-login-page/logo-color.png
  kishanlal-login-page/style.css
Labels: hacktoberfest2022, hacktober-accepted

#139 Added kishanlal-signup-page
  kishanlal-signup-page/index.html
  kishanlal-signup-page/logo-color.png
  kishanlal-signup-page/style.css
Labels: hacktoberfest2022, hacktober-accepted

#140 Gray+Blur Hovering Effects
  Hovering_effects/Sepia/Sepia.css
  Hovering_effects/Sepia/Sepia.html
  Hovering_effects/gray&blur.css
  Hovering_effects/gray&blur.html
Labels: hacktoberfest2022, hacktober-accepted

#146 Added ping game, made using p5 js library
  p5game.html
Labels: hacktoberfest2022, hacktober-accepted
